# Generated by Django 4.2.4 on 2023-08-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_profile_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
