# Generated by Django 4.2.4 on 2023-08-15 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_post_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
    ]
